base_url = "https://urawa72.github.io"

theme = "emily_zola_theme"

title = "urawa72.github.io"
description = "urawa72's blog"

compile_sass = true

build_search_index = false

taxonomies = [
  {name = "categories", rss = false},
  {name = "tags", rss = false},
]

[markdown]
highlight_code = true

[extra]
emily_author = "urawa72"
emily_icon = "/img/profile.jpeg"
emily_favicon = "/img/profile.jpeg"
emily_iconsize = 70
emily_indexposts = 5
emily_dark_mode = true
emily_theme_toggler = true
google_analytics = "G-W4BVR3XW5F"
